### PR TITLE
Document, Fix, and Extend

### PR DESCRIPTION
**Pull request by bryandam**
Add comments to clarify what certain collections are doing.
Add 'Client Health: Unhealthy: Unknown Devices Older than 2 Days'
Add 'Client Health: Unhealthy: Unknown Device GUID'
Add 'Client Health: Unhealthy: Client Uninstalled'
'Client Health: Unhealthy: Clients Not Receiving Policy (Invalid Certificates)': Add all policy error message IDs 5444-5449 and rename collection
'Client Health: Unhealthy: Not on Domain': Fixed to look for Standalone Workstations and Servers based on DomainRole.
'Client Health: Unhealthy: Duplicate System Name': Ignore unknown computers.
'Client Health: Unhealthy: Inactive Clients': Removed unnecessary query and standardized on Active!=1
'Client Health: Unhealthy: Software Updates Compliance Status Missing': Simplified and renamed to match other software update collections.
'Client Health: Unhealthy: AD Discovery: Older Than 7 Days': Excluded devices without the client.
'Client Health: Unhealthy: CCMEval – Failed (All)': Excluded devices without the client.
'Client Health: Unhealthy: CCMEval – No Status Reported': Excluded devices without the client.
'Client Health: Unhealthy: Unassigned Clients': Excluded devices without the client.

### CODE REVIEW

**Comment by Ebag333** [comment]
Mostly looks good.  But a few questions:

```select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where ((DATEDIFF(hh, SMS_R_SYSTEM.AgentTime, getdate()) > 168) and AgentName = \"SMS_AD_SYSTEM_DISCOVERY_AGENT\") and SMS_R_SYSTEM.Client = 1
```

You added the client check.  Intentional?
(There's a few like this.)

From:
```
select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_SYSTEM on SMS_G_System_SYSTEM.ResourceID = SMS_R_System.ResourceId inner join SMS_G_System_COMPUTER_SYSTEM on SMS_G_System_COMPUTER_SYSTEM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_SYSTEM.Domain = '' or SMS_G_System_COMPUTER_SYSTEM.Domain = ''
```
to
```
select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_COMPUTER_SYSTEM on SMS_G_System_COMPUTER_SYSTEM.ResourceId = SMS_R_System.ResourceId where SMS_G_System_COMPUTER_SYSTEM.DomainRole in (0,2)
```

What was wrong with the old query?


NOTE TO SELF: LOOK INTO THIS TRAVESTY!  (Seriously, this is ugly. Original is much uglier!)
```
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.ResourceId not in (select SMS_R_SYSTEM.ResourceID from sms_r_system inner join SMS_UpdateComplianceStatus on SMS_UpdateComplianceStatus.machineid = sms_r_system.resourceid) and SMS_R_System.ResourceId in (select SMS_R_SYSTEM.ResourceID from SMS_R_System inner join SMS_G_System_CH_ClientSummary on SMS_G_System_CH_ClientSummary.ResourceId = SMS_R_System.ResourceId where SMS_G_System_CH_ClientSummary.ClientActiveStatus = 1)";
	
	QueryExpression = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System where SMS_R_System.ResourceId not in (select SMS_R_SYSTEM.ResourceID from sms_r_system inner join SMS_UpdateComplianceStatus on SMS_UpdateComplianceStatus.machineid = sms_r_system.resourceid Join SMS_Softwareupdate on SMS_Softwareupdate.CI_ID = SMS_UpdateComplianceStatus.CI_ID where SMS_UpdateComplianceStatus.Status = 0 or SMS_UpdateComplianceStatus.Status = 1 or SMS_UpdateComplianceStatus.Status = 2 or SMS_UpdateComplianceStatus.Status = 3) and SMS_R_System.ResourceId in (select SMS_R_SYSTEM.ResourceID from SMS_R_System inner join SMS_G_System_CH_ClientSummary on SMS_G_System_CH_ClientSummary.ResourceId = SMS_R_System.ResourceId where SMS_G_System_CH_ClientSummary.ClientActiveStatus = 1)";
```

```
The Widows Update service is not set to automatically start based on a trigger.
```
😆 

```
Sent evaluation results but no longer report as installed.
```
This is the description on the all unhealthy collection.  Probably not the most accurate.

```
Client Health: Unhealthy: Client Uninstalled
```
This collection will catch tons of stuff if the `Clear Client Install Flag` job is turned on. I also think it's duplicated with other collections, so I don't think it's necessary.


The other new collections?  MOST excellent!

**Comment by bryandam** [comment]
'Client Health: Unhealthy: Not on Domain': We talked about this on Slack, the original collection doesn't do what you intended it to.  CM stores the workgroup name in the domain field.  The majority of my devices are not domain joined (in prod) and yet I got 0 results.  The DomainRole field has a specific enumeration and based on testing the 'Standalone' roles are for workgroup computers. 

'Client Health: Unhealthy: Software Updates Compliance Status Missing': We talked about this one on Slack too.  Your intent was to list devices that have never sent a single compliance status.  The subselect was way more complex than it needed to be to accomplish that goal.

The client checks were intentional and it's the reason I added the 'Client Uninstalled' collection.  The description for the 'All Unhealthy' collection was meant for this one ... my bad.  We talked a bit about this yesterday afternoon.  In my environment, and I assume many others, there's a a sizable portion of discovered devices that are not managed by CM so there's nothing unhealthy about them but they keep showing up in a bunch of the collections are looking for stuff that is missing.  

We may ultimately just disagree on this, which is fine, but in a set of collections like this your forced into making assumptions.  As they stand, the assumption is that every discovered device is running Windows 10, is domain joined, and managed by CM.  That's obviously not going to work for every ... or even most ... environments.  If the desire is for these collections to be widely used by people who can't write queries then it has to be relatively painless to change those assumptions.  That means compartmentalizing things like this.

**Comment by Ebag333** [comment]
So change the "Client uninstalled" collection to something like `Client has never sent status messages to the site` and use this query:
```
select SYS.ResourceID,SYS.ResourceType,SYS.Name,SYS.SMSUniqueIdentifier,SYS.ResourceDomainORWorkgroup,SYS.Client from sms_r_system as SYS LEFT join SMS_StatusMessage as stat on stat.machinename = SYS.name OR stat.machinename = SYS.NetbiosName AND stat.ModuleName = "SMS Client"
WHERE stat.ModuleName IS NULL
```

Add this to all unhealthy collections:
```
instance of SMS_CollectionRuleExcludeCollection
{
	ExcludeCollectionID = "SMSCH076";
	RuleName = "Client Health: Unhealthy: Client has never sent status messages to the site";
}
```

Also, move the new collections ABOVE the two all include/exclude collections.  Those I want to keep at the bottom of the MOF (a little organization).

You can just edit the file and push it (either via the web or desktop client), you don't have to close and open a new PR :)

**Comment by Ebag333** [comment]
👍

**Pull request merged**
